### ISSUE TITLE
Gui controls error

### ISSUE THREAD

**Issue by liquidmetalrob** [Lexikos/AutoHotkey-jk#3]
I'm trying to create a Gui with a progress bar but when I try to change the value of it I get the error message:
`Unable to set property 'value' of undefined or null`.

`var myGui = new Gui()`
`myGui.add('Progress', 'vPercent')`
`myGui['Percent'].value = 10`

**Comment by Lexikos** [comment]
In JavaScript, `myGui['Percent']` is equivalent to `myGui.Percent`. Gui has no such property.

I'm not sure whether I documented it anywhere, but looking in the script, I see that `Gui.Prototype.control` provides access to the getter function of `Gui.Prototype.__Item` (i.e. `gui[...]`).
```JavaScript
var myGui = new Gui()
myGui.add('Progress', 'vPercent')
myGui.control('Percent').value = 10
```
`Gui.Control[...]` is how it was done in older AutoHotkey v2-alpha builds.

**Comment by Lexikos** [comment]
I added `control` to the readme.
