### ISSUE TITLE
Optional chaining not supported

### ISSUE THREAD

**Issue by liquidmetalrob** [Lexikos/AutoHotkey-jk#4]
I'm trying to use optional chaining but it's throwing an error.
I'm guessing that means that ES2020 features are not supported. I know AHK-jk uses Edge to run the JS and so I thought maybe I had to install the new version of Edge. So I did that but it hasn't changed anything and now I have two versions of Edge installed somehow.
Is there any way to allow ES2020 features in AHK-jk?

**Comment by Lexikos** [comment]
Whatever works is what you're stuck with. NB:

> Utilizes the JavaScript engine that comes with IE11 or **legacy** Edge.

The readme didn't emphasize this; it does now. This is referring to initial versions of Edge, which were not based on Chromium, unlike what is included in current Windows 10 and 11 builds. The [legacy documentation](https://learn.microsoft.com/en-us/archive/microsoft-edge/legacy/developer/dev-guide/) indicates that it was last updated in October 2018. It will likely never again be updated. From what I can find, it only partially supports ES6 and likely doesn't support anything newer.

Current versions of Edge are Chromium-based, and therefore use the V8 engine. As far as I know, there is no easy-to-use API for hosting the Chromium-based Edge JavaScript engine within an application. I think there is little to no support for IDispatch, which is an essential part of what enables the current iteration of AutoHotkey-jk to work.

Even if you have two versions of Edge installed, it's likely that they're both Chromium-based. Windows has included the Chromium-based version of Edge for several years now.
